CREATE TABLE Reminders (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER_ID TEXT NOT NULL,
    CHANNEL_ID TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP, -- auto-calculated when inserting
    REMIND_TIME DATETIME,
    REMIND_TEXT TEXT,
    REMIND_HAPPENED INTEGER DEFAULT 0  -- 0 = False, 1 = True
);